apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "alertmanager.fullname" . }}
  labels:
    {{- include "alertmanager.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "alertmanager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "alertmanager.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ include "alertmanager.serviceAccountName" . }}
      serviceName: name: {{ include "alertmanager.fullname" . }}-headless
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 9093
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager/config.yml
              subPath: config.yml
            - name: storage
              mountPath: /alertmanager
      volumes:
        - name: config
          configMap:
            name: {{ include "alertmanager.fullname" . }}
{{- if (not .Values.persistence.enabled) }}
        - name: storage
          emptyDir: {}
{{- else }}
      volumeClaimTemplates:
        - metadata:
            name: storage
          spec:
            accessModes:
              {{- toYaml .Values.persistence.accessModes | nindent 4 }}
            resources:
              requests:
                storage: {{ .Values.persistence.size }}
          {{- if .Values.persistence.storageClass }}
          {{- if (eq "-" .Values.persistence.storageClass) }}
            storageClassName: ""
          {{- else }}
            storageClassName: {{ .Values.persistence.storageClass }}
          {{- end }}
          {{- end }}
{{- end -}}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
